name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Install dependencies
      run: go mod download
    - name: Run Tests
      run: go test -v ./...

  build:
    name: Build Cross-Platform
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build
      run: bash scripts/build.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ephemeral-binaries
        path: dist/
